spring:
  application:
    name: fly-genius
  datasource:
    url: jdbc:mysql://localhost:3306/ai-code-genius?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: root
  profiles:
    active: local
server:
  port: 8100
  servlet:
    context-path: /api

# knife4j配置
springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - com.flycode.flygenius.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    root: info
  config: classpath:logback-spring.xml

